version: "2"

run:
  timeout: 3m
  tests: false
  skip-dirs:
    - vendor
    - deploy
    - .github
    - build
    - dist
    - mocks

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
