version: "2"

run:
  timeout: 3m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: ^vendor/
    - path: ^deploy/
    - path: ^\.github/
    - path: ^build/
    - path: ^dist/
    - path: ^mocks/
  max-issues-per-linter: 0
  max-same-issues: 0
