version: 2

run:
  timeout: 3m
  tests: false

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - vendor
    - deploy
    - .github
    - build
    - dist
    - mocks
  max-issues-per-linter: 0
  max-same-issues: 0
