name: 'Template:Validate GOLANG codebase'

on:
  workflow_call:

jobs:
  validate:
    name: 'Validate golang layer'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: 'Install Golang'
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - name: 'golangci lint'
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          args: --timeout 4m --config .golangci.yaml
