name: 'Template:CI GOLANG tool'

on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/tpl_validate_golang.yml
    secrets: inherit

  build-push-image:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/tpl_build_container_images.yml
    secrets: inherit
